export default [
    {
        id: 1,
        type: 'TileOne',
        title: 'Tile 1',
        description: 'Tile 1 description dsfsadfsadfas dfsadf asdfasdfasdfdas',
        tileUrl: 'https://www.google.com/',
        tilePictureUrl: "https://images.freeimages.com/images/small-previews/2fe/butterfly-1390152.jpg",
        positionX: 50,
        positionY: 50,
        tileWidth: 100,
        tileHeight: 200,
    },
    {
        id: 2,
        type: 'TileOne',
        title: 'Tile 2',
        description: 'Tile 2 description adsfasdfas adsfadsfads fsadf asdfasd fasd',
        tileUrl: 'https://www.google.com/',
        tilePictureUrl: "https://images.freeimages.com/images/small-previews/2fe/butterfly-1390152.jpg",
        positionX: 300,
        positionY: 100,
        tileWidth: 200,
        tileHeight: 200,
    },
    {
        id: 3,
        type: 'TileOne',
        title: 'Tile 3',
        description: 'Tile 3 description asdfasdfasdfasdfasdf asdfdsaasd ffdsaas dfdsafdsafsdaf',
        tileUrl: 'https://www.google.com/',
        tilePictureUrl: "https://images.freeimages.com/images/small-previews/2fe/butterfly-1390152.jpg",
        positionX: 200,
        positionY: 400,
        tileWidth: 400,
        tileHeight: 200,
    },
    {
        id: 4,
        type: 'TileTwo',
        title: 'Tile 4',
        description: 'Tile 4 description',
        tileUrl: 'https://www.google.com/',
        tilePictureUrl: "https://images.freeimages.com/images/small-previews/2fe/butterfly-1390152.jpg",
        positionX: 700,
        positionY: 300,
        tileWidth: 300,
        tileHeight: 200,
    },
]
